export const ENGINEERING_FACTS = [
  "kVA to Amps (3-Phase 400V): I = 1000 / (1.732 × 400) = 1.44 Amps per kVA.",
  "kVA to Amps (1-Phase 220V): I = 1000 / 220 = 4.55 Amps per kVA.",
  "Motor Torque Formula: Torque (Nm) = (9550 × Power_kW) / RPM.",
  "Synchronous Speed Formula: RPM = (120 × Frequency) / Poles.",
  "Motor Power (3-Phase): P (kW) = (V × I × PF × 1.732) / 1000.",
  "Voltage Drop (3-Phase): Vd = (1.732 × K × L × I) / Area (where K is resistivity).",
  "IP65 Rating: '6' means dust-tight, '5' means protection against water jets from any direction.",
  "Skin Effect: AC current tends to flow on the outer surface of a conductor, increasing effective resistance.",
  "Ferranti Effect: Voltage at receiving end of a long, lightly loaded line is higher than at sending end.",
  "ABB DTC (Direct Torque Control): Updates torque calculations 40,000 times per second.",
  "Siemens 3VA Series: 3VA1 (Thermal-Magnetic) and 3VA2 (Electronic) protection.",
  "Type C MCB: Designed to trip at 5 to 10 times the rated current (standard industrial).",
  "Type D MCB: Trips at 10 to 20 times rated current, used for high-inrush loads.",
  "Polarization Index (PI): Ratio of IR at 10m vs 1m; PI > 2.0 is considered good.",
  "Star-Delta Starting: Reduces starting current and torque to exactly 1/3 of DOL values.",
  "3rd Harmonics: Additive in the neutral wire of a 3-phase system, can cause overheating.",
  "SF6 Gas: Best insulator for high-voltage switchgear but a potent greenhouse gas.",
  "4-20mA Loops: The 'live zero' allows for detection of wire breaks (unlike 0-10V).",
  "Motor Slip: Difference between synchronous speed and rotor speed, needed for torque.",
  "IEC 60364-5-52: The primary international standard for cable sizing.",
  "Power Factor Correction: Adding capacitors reduces reactive power (kVAR) drawn.",
  "VSD Braking Resistor: Dissipates kinetic energy as heat during fast deceleration.",
  "Safe Torque Off (STO): A hardware-level safety function in VSDs rated SIL 3 / PL e.",
  "Modbus RTU: Widely used industrial protocol over RS-485 serial lines.",
  "Cable Derating: Grouping multiple cables reduces their heat dissipation capability.",
  "Busbar Skin Effect: Large busbars are often hollow to improve current distribution.",
  "NEMA 4X: Often superior to IP66 as it includes corrosion and ice resistance tests.",
  "Residual Current Device (RCD): 30mA is the standard threshold for life-safety.",
  "Arc Flash: Dangerous energy release from an electrical arc; requires specific PPE.",
  "Megger Trivia: 'Megging' is the global industry term for insulation testing.",
  "Motor Insulation Class F: Maximum operating temperature of 155°C.",
  "Rule of Thumb (400V 3ph Motor): FLA is roughly 1.5 to 2 times the kW rating.",
  "Fall-of-Potential: Standard 3-stake test for measuring earth electrode resistance.",
  "Current imbalance in 3-phase motors should ideally be less than 5%.",
  "VSDs can save up to 50% energy in centrifugal pump and fan applications.",
  "Efficiency of IE3 Premium Efficiency motors is typically > 90% for > 7.5kW.",
  "Standard cable colors (IEC 60446): L1=Brown, L2=Black, L3=Grey, N=Blue, PE=Green/Yellow.",
  "A 10°C rise in operating temperature halves the life of motor insulation.",
  "Transformer efficiency is highest when copper losses equal iron losses.",
  "High resistance at terminal connections is a leading cause of electrical fires.",
  "Soft Starters only control voltage; VSDs control both voltage and frequency.",
  "The 62% rule in earth testing is based on the mathematical curve of potential.",
  "Inverters (VSD) generate harmonics that can cause noise in sensitive sensors.",
  "EMC cables with 360° grounding screens are required for VSD motor leads.",
  "The 'Neutral' is theoretically at earth potential but often carries volts due to imbalance.",
  "Capacitors can hold a lethal charge for minutes after power is disconnected.",
  "Direct-on-Line (DOL) starting can draw 6-8 times the motor's full load current.",
  "Short circuit ratings (Icu) of breakers must exceed the system's fault level.",
  "Contactors have a limited number of electrical operations (typically 1 million).",
  "Silver plating on busbar joints prevents oxidation and maintains low resistance."
];

export function getRandomFact() {
  return ENGINEERING_FACTS[Math.floor(Math.random() * ENGINEERING_FACTS.length)];
}
